added scenarios via repo

diff --git a/install b/install
--- a/install
+++ b/install
@@ -43,6 +43,15 @@ then
   ln -sf $LIGHTNING_INSTALLATION_DIRECTORY/lightning/lightning-launcher $SYMLINK_INSTALLATION_DIRECTORY/lightning
 
   echo $(tput setaf 0)$(tput setab 2) "Lightnig was properly installed" $(tput sgr 0)
+  
+  # ptoribi: get the last version of the scenarios from the GitHub repository
+  source LIGHTNING_INSTALLATION_DIRECTORY/variables.conf
+  git clone $GITHUB_SCENARIOS $LIGHTNING_INSTALLATION_DIRECTORY/scenarios
+  if [ $? != 0 ]
+  then
+    echo $(tput setaf 0)$(tput setab 1) "Error while getting scenarios from GitHub, are you connected to the internet?" $(tput sgr 0)
+  fi
+  
 else
   echo $(tput setaf 0)$(tput setab 1) "Lightnig has to be installed as root or using "sudo"" $(tput sgr 0)
 fi
