fixed disaster when executing lightning update without internet connection

diff --git a/update b/update
--- a/update
+++ b/update
@@ -28,8 +28,13 @@ mkdir /tmp/lightning-tmp
 # ptoribi: the last version of Lightning will be downloaded from GitHub
 git clone $GITHUB /tmp/lightning-tmp
 
-# ptoribi: the version currently installed in the system will be uninstalled
-sudo $(dirname $(readlink -f $(which lightning)))/uninstall
+if [ $? == 0 ]
+then
+  # ptoribi: the version currently installed in the system will be uninstalled
+  sudo $(dirname $(readlink -f $(which lightning)))/uninstall
 
-# ptoribi: the new version will be installed
-sudo /tmp/lightning-tmp/install
+  # ptoribi: the new version will be installed
+  sudo /tmp/lightning-tmp/install
+else
+  echo $(tput setaf 0)$(tput setab 1) "Error while getting lightning from GitHub, are you connected to the internet?" $(tput sgr 0)
+fi
